# Generated by Django 4.2.2 on 2023-06-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
